version: '3.8'

services:
  web:
    build: .
    command: python3 run.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"

volumes:
  postgres_data: